### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by kgryte** [datasets-io/iris-setosa#1]
Unless you think otherwise, for these modules, I am fine with the README showing `[...]`, so as to indicate that the data structure is an `object` containing `arrays`. Let me know whether you think we should actually include numeric values in those `arrays`.

**Comment by Planeshifter** [comment]
Sounds fine to me, too. Package should be ready to land on npm.

**Comment by kgryte** [comment]
Awesome. Thanks for reviewing!
